SidangMahasiswa.MVC/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace SidangMahasiswa.MVC.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

SidangMahasiswa.MVC/Controllers/JadwalSIdangController.cs
using DataAccess;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using ViewModel;

namespace SidangMahasiswa.MVC.Controllers
{
    public class JadwalSIdangController : Controller
    {
        // GET: JadwalSIdang
        public ActionResult Index(string searchString, int? page, string currentFilter)
        {
            if (searchString != null)
            {
                page = 1;
            }
            else
            {
                searchString = currentFilter;
            }
            ViewBag.CurrentFilter = searchString;
            List<JadwalSidangViewModel> listJad = new List<JadwalSidangViewModel>();
            listJad = JadwalSidangRepo.All(searchString);

            if (!String.IsNullOrEmpty(searchString))
            {
                listJad = listJad.Where(a => a.Mahasiswa_Nama.ToUpper().Contains(searchString.ToUpper())).ToList();
                if (listJad.Count() != 0)
                {
                    TempData["tidakAda"] = null;
                }
                else
                {
                    TempData["tidakAda"] = "Data tidak ditemukan";
                }
            }
            else
            {
                listJad = JadwalSidangRepo.All(searchString);
            }

            return View();
        }

        public ActionResult List()
        {
            return PartialView("_List", JadwalSidangRepo.AllList()) ;
        }

        public ActionResult Create()
        {
            ViewBag.MahasiswaList = new SelectList(MahasiswaRepo.All(), "Id", "Nama");
            ViewBag.TugasAkhirList = new SelectList(TugasAkhirRepo.ByMahasiswa(0), "Id", "Pembimbing", "Judul");
            return PartialView("_Create", new JadwalSidangViewModel());

        }

        public ActionResult GetByMahasiswa(long mahasiswaId)
        {
            return View(TugasAkhirRepo.ByMahasiswa(mahasiswaId));
        }

        [HttpPost]
        public ActionResult Create(JadwalSidangViewModel model)
        {

            ResponseResult result = JadwalSidangRepo.Update(model);
            return Json(new
            {
                success = result.Success,
                message = result.Message,
                entity = result.Entity
            }, JsonRequestBehavior.AllowGet);

        }

        public ActionResult Edit(int id)
        {
            JadwalSidangViewModel model = JadwalSidangRepo.ById(id);
            ViewBag.MahasiswaList = new SelectList(MahasiswaRepo.All(), "Id", "Nama");
            ViewBag.TugasAkhirList = new SelectList(TugasAkhirRepo.ByMahasiswa(model.MahasiswaId), "Id", "Pembimbing", "Judul");
            return PartialView("_Edit", model);
        }

        [HttpPost]
        public ActionResult Edit(JadwalSidangViewModel model)
        {
            ResponseResult result = JadwalSidangRepo.Update(model);
            return Json(new
            {
                success = result.Success,
                message = result.Message,
                entity = result.Entity
            }, JsonRequestBehavior.AllowGet);
        }

        public ActionResult Delete(int id)
        {
            return PartialView("_Delete", JadwalSidangRepo.ById(id));
        }

        [HttpPost]
        public ActionResult Delete(JadwalSidangViewModel model)
        {
            ResponseResult result = JadwalSidangRepo.Delete(model);
            return Json(new
            {
                success = result.Success,
                message = result.Message,
                entity = result.Entity
            }, JsonRequestBehavior.AllowGet);
        }

    }
}

SidangMahasiswa.MVC/Controllers/MahasiswaController.cs
using DataAccess;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using ViewModel;

namespace SidangMahasiswa.MVC.Controllers
{
    public class MahasiswaController : Controller
    {
        // GET: Mahasiswa
        public ActionResult Index()
        {
            return View();
        }
        public ActionResult List()
        {
            return PartialView("_List", MahasiswaRepo.All());
        }
        public ActionResult Create()
        {
            return PartialView("_Create", new MahasiswaViewModel());
        }
        [HttpPost]
        public ActionResult Create(MahasiswaViewModel model)
        {
            ResponseResult result = MahasiswaRepo.Update(model);
            return Json(new
            {
                success = result.Success,
                message = result.Message,
                entity = result.Entity
            }, JsonRequestBehavior.AllowGet);
        }
        public ActionResult Edit(int id)
        {
            return PartialView("_Edit", MahasiswaRepo.ById(id));
        }

        [HttpPost]
        public ActionResult Edit(MahasiswaViewModel model)
        {
            ResponseResult result = MahasiswaRepo.Update(model);
            return Json(new
            {
                success = result.Success,
                message = result.Message,
                entity = result.Entity
            }, JsonRequestBehavior.AllowGet);
        }
        public ActionResult Delete(int id)
        {
            return PartialView("Delete", MahasiswaRepo.ById(id));
        }
        [HttpPost]
        public ActionResult Delete(MahasiswaViewModel model)
        {
            ResponseResult result = MahasiswaRepo.Delete(model);
            return Json(new
            {
                success = result.Success,
                message = result.Message,
                entity = result.Entity
            }, JsonRequestBehavior.AllowGet);
        }
    }
}

SidangMahasiswa.MVC/Controllers/TugasAkhirController.cs
using DataAccess;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using ViewModel;

namespace SidangMahasiswa.MVC.Controllers
{
    public class TugasAkhirController : Controller
    {
        // GET: TugasAkhir
        public ActionResult Index()
        {
            return View();
        }
        public ActionResult List()
        {
            return PartialView("_List", TugasAkhirRepo.All());
        }

        public ActionResult Create()
        {
            ViewBag.MahasiswaList = new SelectList(TugasAkhirRepo.AllMahasiswa(), "Id", "Nama");
            return PartialView("_Create", new TugasAkhirViewModel());
        }

        [HttpPost]
        public ActionResult Create(TugasAkhirViewModel model)
        {

            ResponseResult result = TugasAkhirRepo.Update(model);
            return Json(new
            {
                success = result.Success,
                message = result.Message,
                entity = result.Entity
            }, JsonRequestBehavior.AllowGet);

        }

        public ActionResult Edit(int id)
        {
            TugasAkhirViewModel model = TugasAkhirRepo.ById(id);
            ViewBag.MahasiswaList = new SelectList(TugasAkhirRepo.AllMahasiswa(), "Id", "Nama");
            return PartialView("_Edit", model);
        }

        [HttpPost]
        public ActionResult Edit(TugasAkhirViewModel model)
        {
            ResponseResult result = TugasAkhirRepo.Update(model);
            return Json(new
            {
                success = result.Success,
                message = result.Message,
                entity = result.Entity
            }, JsonRequestBehavior.AllowGet);
        }

        public ActionResult Delete(int id)
        {
            return PartialView("_Delete", TugasAkhirRepo.ById(id));
        }

        [HttpPost]
        public ActionResult Delete(TugasAkhirViewModel model)
        {
            ResponseResult result = TugasAkhirRepo.Delete(model);
            return Json(new
            {
                success = result.Success,
                message = result.Message,
                entity = result.Entity
            }, JsonRequestBehavior.AllowGet);
        }
    }
}

SidangMahasiswa.MVC/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

SidangMahasiswa.MVC/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

SidangMahasiswa.MVC/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="jumbotron">
    <h1>ASP.NET</h1>
    <p class="lead">ASP.NET is a free web framework for building great Web sites and Web applications using HTML, CSS and JavaScript.</p>
    <p><a href="https://asp.net" class="btn btn-primary btn-lg">Learn more &raquo;</a></p>
</div>

<div class="row">
    <div class="col-md-4">
        <h2>Getting started</h2>
        <p>
            ASP.NET MVC gives you a powerful, patterns-based way to build dynamic websites that
            enables a clean separation of concerns and gives you full control over markup
            for enjoyable, agile development.
        </p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301865">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Get more libraries</h2>
        <p>NuGet is a free Visual Studio extension that makes it easy to add, remove, and update libraries and tools in Visual Studio projects.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301866">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Web Hosting</h2>
        <p>You can easily find a web hosting company that offers the right mix of features and price for your applications.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301867">Learn more &raquo;</a></p>
    </div>
</div>

SidangMahasiswa.MVC/Views/JadwalSIdang/GetByMahasiswa.cshtml
@{
    Layout = null;
}

@model IEnumerable<ViewModel.TugasAkhirViewModel>
<option value="">Select Nama</option>

@foreach (var item in Model)
{
    <option value="@item.Id">@item.Nama</option>
}

SidangMahasiswa.MVC/Views/Mahasiswa/Delete.cshtml
@model ViewModel.MahasiswaViewModel

@using (Html.BeginForm("Delete", "Mahasiswa", FormMethod.Post,
    new { id = "form-delete", name = "form-delete" }))
{
    @Html.AntiForgeryToken()
    <style>
        .glyphicon-trash {
            font-size: 80px;
            color: darkred;
        }
    </style>

    <div class="form-horizontal">

        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)
        <div class="row">
            <div class="panel-heading">
                <div class="col-md-3" style="margin-left:8%; margin-top:2%;">
                    <span class="glyphicon glyphicon-trash"></span>
                </div>
                <div class="col-md-8 " style="color:darkred">
                    <span>Apakah anda yakin ingin menghapus </span>
                    <br />
                    <b> @Html.DisplayFor(Model => Model.Nama)<a> ?</a></b>
                </div>
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-offset-8 col-md-10">
                <div class="input-group">
                    <input type="button" value="Tidak" onclick="location.href='@Url.Action("Index")';" class="btn btn-warning" />
                    <input type="submit" value="Ya   " class="btn btn-danger" />
                </div>
            </div>
        </div>
    </div>

}

<script type="text/javascript">
    $("#form-delete").submit(function () {
        $.ajax({
            url: this.action,
            type: this.method,
            data: $(this).serialize(),
            success: function (result) {
                if (result.success) {
                    $(".modal").modal("hide");
                    location.reload();
                    //GetList();
                } else {
                    alert("error! " + result.message);
                }
            }
        });
        return false;
    });

</script>

SidangMahasiswa.MVC/Views/Mahasiswa/_Create.cshtml
@model ViewModel.MahasiswaViewModel

<style>
    .btn-warning {
        background-color: #FF7D33;
        padding-left: 20px;
    }

    .btn-primary {
        background-color: midnightblue;
    }
</style>
@using (Html.BeginForm("Create", "Mahasiswa", FormMethod.Post, new { id = "form-create", name = "form-create" }))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">

        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Nama, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Nama, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Nama, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Nim, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Nim, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Nim, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="modal-footer">
            <div class="btn-group navbar-right" style="margin:0">
                <button type="button" class="btn btn-warning" data-dismiss="modal">Batal</button>
                <button type="submit" class="btn btn-primary">Save</button>
            </div>
        </div>
    </div>
}

<script type="text/javascript">
    $("#form-create").submit(function () {
        $.ajax({
            url: this.action,
            type: this.method,
            data: $(this).serialize(),
            success: function (result) {
                if (result.success) {
                    alert("Save Successfull! Name: " + result.entity.Nama);
                    $(".modal").modal("hide");
                    GetList();
                }
                else {
                    alert("Error" + result.message);
                }
            }
        });
        return false;
    });
</script>

SidangMahasiswa.MVC/Views/Mahasiswa/_Edit.cshtml
@model ViewModel.MahasiswaViewModel


@using (Html.BeginForm("Edit", "Mahasiswa", FormMethod.Post,
    new { id = "form-edit", name = "form-edit" }))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.Nama, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Nama, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Nama, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Nim, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Nim, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Nim, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="modal-footer">
            <div class="btn-group navbar-right" style="margin:0">
                <button type="button" class="btn btn-warning" data-dismiss="modal">Batal</button>
                <button type="submit" class="btn btn-primary">Save</button>
            </div>
        </div> 
    </div>
}

<script type="text/javascript">
    $("#form-edit").submit(function () {
        $.ajax({
            url: this.action,
            type: this.method,
            data: $(this).serialize(),
            success: function (result) {
                if (result.success) {
                    alert("Edit Successfull! Name: " + result.entity.Nama);
                    $(".modal").modal("hide");
                    GetList();
                }
                else {
                    alert("Error" + result.message);
                }
            }
        });
        return false;
    });
</script>

SidangMahasiswa.MVC/Views/Mahasiswa/_List.cshtml
@model IEnumerable<ViewModel.MahasiswaViewModel>

    <head>
        <style>
            table {
                font-family: arial, sans-serif;
                border-collapse: collapse;
                width: 100%;
            }


            td {
                border-top: 3px solid midnightblue;
                text-align: left;
                padding: 8px;
            }

            tr:nth-child(even) {
                background-color: #dddddd;
                width: 100%;
            }

            body {
                margin: 0;
            }
        </style>
    </head>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Nama)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Nim)
        </th>
        <th>
            #
        </th>
       
    </tr>
    <tbody>
        @foreach (var item in Model)
        {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Nama)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Nim)
            </td>
            <td>
                <div class="dropdown">
                    <button type="button" class="btn btn-primary dropdown-toggle" id="dropDownMenu1"
                            data-toggle="dropdown" aria-haspopup="true" aria-expanded="true">
                        More
                        <span class="caret"></span>
                    </button>
                    <ul class="dropdown-menu" aria-labelledby="dropDownMenu1">
                        <li><a class="btn-edit" data-id="@item.Id">Ubah</a></li>
                        <li><a class="btn-delete" data-id="@item.Id">Hapus</a></li>

                    </ul>
                </div>
            </td>
        </tr>
        }
    </tbody>
</table>
<script type="text/javascript">
    $(".btn-edit").click(function () {
        $.ajax({
            url: '@Url.Action("Edit", "Mahasiswa")',
            type: 'get',
            data: { id: $(this).attr("data-id") },
            success: function (result) {
                $(".modal-title").html("Edit");
                $(".modal-body").html(result);
                $(".modal").modal("show");
            }
        });
    });

     $(".btn-delete").click(function () {
        $.ajax({
            url: '@Url.Action("Delete", "Mahasiswa")',
            type: 'get',
            data: { id: $(this).attr("data-id") },
            success: function (result) {
                $(".modal-title").html("Hapus ?");
                $(".modal-body").html(result);
                $(".modal").modal("show");
            }
        });
    });

</script>

SidangMahasiswa.MVC/Views/TugasAkhir/_Create.cshtml
@model ViewModel.TugasAkhirViewModel

    <style>
        .btn-warning {
            background-color: #FF7D33;
            padding-left: 20px;
        }

        .btn-primary {
            background-color: midnightblue;
        }
    </style>
@using (Html.BeginForm("Create", "TugasAkhir", FormMethod.Post, new { id = "form-create", name = "form-create" })) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            <div class="col-md-10">
                <label>Nama Mahasiswa</label>
                @Html.DropDownListFor(model => model.MahasiswaId,
                       (IEnumerable<SelectListItem>)ViewBag.MahasiswaList, "--Pilih Nama--",
                       new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.MahasiswaId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-10">
                <label>Kategori</label>
                @Html.EditorFor(model => model.Kategori, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Kategori, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-10">
                <label>Pembimbing</label>
                @Html.EditorFor(model => model.Pembimbing, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Pembimbing, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-10">
                <label>Judul</label>
                @Html.EditorFor(model => model.Judul, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Judul, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="modal-footer">
            <div class="btn-group navbar-right" style="margin:0">
                <button type="button" class="btn btn-warning" data-dismiss="modal">Batal</button>
                <button type="submit" class="btn btn-primary">Save</button>
            </div>
        </div>
    </div>
}

<script type="text/javascript">
    $("#form-create").submit(function () {
        $.ajax({
            url: this.action,
            type: this.method,
            data: $(this).serialize(),
            success: function (result) {
                if (result.success) {
                    alert("Save Successfull! Name: " + result.entity.Nama);
                    $(".modal").modal("hide");
                    GetList();
                }
                else {
                    alert("Error" + result.message);
                }
            }
        });
        return false;
    });
</script>

SidangMahasiswa.MVC/Views/TugasAkhir/_Delete.cshtml
@model ViewModel.TugasAkhirViewModel

@using (Html.BeginForm("Delete", "TugasAkhir", FormMethod.Post,
    new { id = "form-delete", name = "form-delete" }))
{
    @Html.AntiForgeryToken()
    <style>
        .glyphicon-trash {
            font-size: 80px;
            color: darkred;
        }
    </style>

    <div class="form-horizontal">

        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)
        <div class="row">
            <div class="panel-heading">
                <div class="col-md-3" style="margin-left:8%; margin-top:2%;">
                    <span class="glyphicon glyphicon-trash"></span>
                </div>
                <div class="col-md-8 " style="color:darkred">
                    <span>Apakah anda yakin ingin menghapus </span>
                    <br />
                    <b> @Html.DisplayFor(Model => Model.Nama)<a> ?</a></b>
                </div>
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-offset-8 col-md-10">
                <div class="input-group">
                    <input type="button" value="Tidak" onclick="location.href='@Url.Action("Index")';" class="btn btn-warning" />
                    <input type="submit" value="Ya   " class="btn btn-danger" />
                </div>
            </div>
        </div>
    </div>
}

<script type="text/javascript">
    $("#form-delete").submit(function () {
        $.ajax({
            url: this.action,
            type: this.method,
            data: $(this).serialize(),
            success: function (result) {
                if (result.success) {
                    $(".modal").modal("hide");
                    location.reload();
                    //GetList();
                } else {
                    alert("error! " + result.message);
                }
            }
        });
        return false;
    });

</script>

SidangMahasiswa.MVC/Views/TugasAkhir/_Edit.cshtml
@model ViewModel.TugasAkhirViewModel


@using (Html.BeginForm("Edit", "TugasAkhir", FormMethod.Post,
    new { id = "form-edit", name = "form-edit" }))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            <div class="col-md-10">
                <label>Nama Mahasiswa</label>
                @Html.DropDownListFor(model => model.MahasiswaId,
        (IEnumerable<SelectListItem>)ViewBag.MahasiswaList, "Select Nama",
        new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.MahasiswaId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-10">
                <label>Kategori</label>
                @Html.EditorFor(model => model.Kategori, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Kategori, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-10">
                <label>Pembimbing</label>
                @Html.EditorFor(model => model.Pembimbing, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Pembimbing, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-10">
                <label>Judul</label>
                @Html.EditorFor(model => model.Judul, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Judul, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="modal-footer">
            <div class="btn-group navbar-right" style="margin:0">
                <button type="button" class="btn btn-warning" data-dismiss="modal">Batal</button>
                <button type="submit" class="btn btn-primary">Save</button>
            </div>
        </div>
    </div>
}

<script type="text/javascript">
    $("#form-edit").submit(function () {
        $.ajax({
            url: this.action,
            type: this.method,
            data: $(this).serialize(),
            success: function (result) {
                if (result.success) {
                    alert("Edit Successfull! Name: " + result.entity.Nama);
                    $(".modal").modal("hide");
                    GetList();
                }
                else {
                    alert("Error" + result.message);
                }
            }
        });
        return false;
    });
</script>

SidangMahasiswa.MVC/Views/TugasAkhir/_List.cshtml
@model IEnumerable<ViewModel.TugasAkhirViewModel>

    <head>
        <style>
            table {
                font-family: arial, sans-serif;
                border-collapse: collapse;
                width: 100%;
            }


            td {
                border-top: 3px solid midnightblue;
                text-align: left;
                padding: 8px;
            }

            tr:nth-child(even) {
                background-color: #dddddd;
                width: 100%;
            }

            body {
                margin: 0;
            }
        </style>
    </head>
<table class="table">
    <tr>
        <th>
            Nama
        </th>
        <th>
            Kategori
        </th>
        <th>
            Pembimbing
        </th>
        <th>
            Judul
        </th>
        <th>
            #
        </th>
        
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Nama)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Kategori)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Pembimbing)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Judul)
        </td>
        <td>
            <div class="dropdown">
                <button type="button" class="btn btn-primary dropdown-toggle" id="dropDownMenu1"
                        data-toggle="dropdown" aria-haspopup="true" aria-expanded="true">
                    More
                    <span class="caret"></span>
                </button>
                <ul class="dropdown-menu" aria-labelledby="dropDownMenu1">
                    <li><a class="btn-edit" data-id="@item.Id">Ubah</a></li>
                    <li><a class="btn-delete" data-id="@item.Id">Hapus</a></li>

                </ul>
            </div>
        </td>
    </tr>
}

</table>
<script type="text/javascript">
    $(".btn-edit").click(function () {
        $.ajax({
            url: '@Url.Action("Edit", "TugasAkhir")',
            type: 'get',
            data: { id: $(this).attr("data-id") },
            success: function (result) {
                $(".modal-title").html("Edit");
                $(".modal-body").html(result);
                $(".modal").modal("show");
            }
        });
    });

     $(".btn-delete").click(function () {
        $.ajax({
            url: '@Url.Action("Delete", "TugasAkhir")',
            type: 'get',
            data: { id: $(this).attr("data-id") },
            success: function (result) {
                $(".modal-title").html("Hapus ?");
                $(".modal-body").html(result);
                $(".modal").modal("show");
            }
        });
    });

</script>